var searchData=
[
  ['facade_2ehpp_0',['facade.hpp',['../facade_8hpp.html',1,'']]],
  ['factory_1',['Factory',['../classgofpp_1_1Factory.html',1,'gofpp']]],
  ['factory_2ehpp_2',['factory.hpp',['../factory_8hpp.html',1,'']]],
  ['fails_20to_20upload_20to_20gpu_3',['(4) Font atlas texture fails to upload to GPU.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md166',1,'']]],
  ['faq_4',['Support, Frequently Asked Questions (FAQ)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md229',1,'']]],
  ['faq_20frequently_20asked_20questions_5',['FAQ (Frequently Asked Questions)',['../md_vendor_2imgui_2docs_2FAQ.html',1,'']]],
  ['faq_2emd_6',['FAQ.md',['../FAQ_8md.html',1,'']]],
  ['features_7',['features',['..//home/runner/work/gofpp/gofpp/vendor/NTest/vendor/NCLI/README.md#autotoc_md282',1,'Features'],['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md268',1,'Features'],['../index.html#autotoc_md32',1,'Features'],['../proxy_8hpp.html#features',1,'Key Features']]],
  ['file_8',['1. Create a test file',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md273',1,'']]],
  ['filename_20due_20to_20use_20of_20tt_20tt_20or_20unexpected_20working_20directory_9',['(1) Invalid filename due to use of &lt;tt&gt;\&lt;/tt&gt; or unexpected working directory.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md163',1,'']]],
  ['filenames_10',['About Filenames',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md203',1,'']]],
  ['flow_11',['8. Example Contribution Flow',['../md_docs_2CONTRIBUTING.html#autotoc_md17',1,'']]],
  ['flyweight_2ehpp_12',['flyweight.hpp',['../flyweight_8hpp.html',1,'']]],
  ['flyweightfactory_13',['FlyweightFactory',['../classgofpp_1_1FlyweightFactory.html',1,'gofpp']]],
  ['font_20atlas_20texture_20fails_20to_20upload_20to_20gpu_14',['(4) Font atlas texture fails to upload to GPU.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md166',1,'']]],
  ['font_20data_20embedded_20in_20source_20code_15',['Loading Font Data Embedded In Source Code',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md181',1,'']]],
  ['font_20data_20from_20memory_16',['Loading Font Data from Memory',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md178',1,'']]],
  ['font_20links_17',['Font Links',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md216',1,'']]],
  ['font_20than_20the_20default_18',['Q: How can I load a different font than the default?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md131',1,'']]],
  ['fonts_19',['fonts',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md159',1,'Dear ImGui: Using Fonts'],['../md_vendor_2imgui_2docs_2FONTS.html',1,'FONTS'],['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md217',1,'ICON FONTS'],['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md210',1,'Metrics/Debugger-&gt;Fonts'],['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md219',1,'MONOSPACE FONTS'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md137',1,'Q: How can I load multiple fonts?'],['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md218',1,'REGULAR FONTS'],['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md184',1,'Using Icon Fonts']]],
  ['fonts_20included_20in_20repository_20',['Credits/Licenses For Fonts Included In Repository',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md214',1,'']]],
  ['fonts_20loading_20instructions_21',['Fonts Loading Instructions',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md175',1,'']]],
  ['fonts_20svginot_22',['Using OpenType SVG fonts (SVGinOT)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md263',1,'']]],
  ['fonts_20system_20in_201_2092_20june_202025_23',['New! Dynamic Fonts system in 1.92 (June 2025)',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md169',1,'']]],
  ['fonts_20text_24',['Q&amp;A: Fonts, Text',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md129',1,'']]],
  ['fonts_2emd_25',['FONTS.md',['../FONTS_8md.html',1,'']]],
  ['for_20fonts_20included_20in_20repository_26',['Credits/Licenses For Fonts Included In Repository',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md214',1,'']]],
  ['for_20toying_20with_20settings_20for_20developers_27',['Testbed for toying with settings (for developers)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md259',1,'']]],
  ['for_20tt_20imguibackendflags_5frendererhastextures_20tt_201_2092_28',['Rendering: Adding support for &lt;tt&gt;ImGuiBackendFlags_RendererHasTextures&lt;/tt&gt; (1.92+)',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md57',1,'']]],
  ['framework_29',['Not a Framework',['../md_docs_2PHILOSOPHY.html#autotoc_md27',1,'']]],
  ['freetype_20rasterizer_20imgui_5ffreetype_30',['Using FreeType Rasterizer (imgui_freetype)',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md190',1,'']]],
  ['frequently_20asked_20questions_31',['FAQ (Frequently Asked Questions)',['../md_vendor_2imgui_2docs_2FAQ.html',1,'']]],
  ['frequently_20asked_20questions_20faq_32',['Support, Frequently Asked Questions (FAQ)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md229',1,'']]],
  ['from_20memory_33',['Loading Font Data from Memory',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md178',1,'']]],
  ['function_34',['Rendering: Implementing your RenderDrawData function',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md56',1,'']]]
];
