var searchData=
[
  ['m_0',['m',['../structgofpp_1_1MultiThreaded.html#a66077cebad35cbd1239d84dafc1d0f77',1,'gofpp::MultiThreaded']]],
  ['machine_20without_20mouse_20keyboard_20or_20screen_20input_20share_20remote_20display_1',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['macos_2',['macos',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md254',1,'macOS'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md247',1,'macOS'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_allegro5/README.md#autotoc_md236',1,'On Ubuntu 14.04+ and macOS']]],
  ['maths_20operators_20with_20imvec2_3',['Q: How can I use maths operators with ImVec2?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md117',1,'']]],
  ['maths_20types_20instead_20of_20imvec2_20imvec4_4',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md120',1,'']]],
  ['mediator_5',['Mediator',['../classgofpp_1_1Mediator.html',1,'gofpp']]],
  ['mediator_2ehpp_6',['mediator.hpp',['../mediator_8hpp.html',1,'']]],
  ['memento_7',['memento',['../structgofpp_1_1Memento.html',1,'gofpp::Memento&lt; State &gt;'],['../structgofpp_1_1Memento.html#a5c5d3d5c98bd90927408f98a5a5aba8f',1,'gofpp::Memento::Memento()']]],
  ['memento_2ehpp_8',['memento.hpp',['../memento_8hpp.html',1,'']]],
  ['memory_9',['Loading Font Data from Memory',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md178',1,'']]],
  ['metrics_20debugger_20fonts_10',['Metrics/Debugger-&gt;Fonts',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md210',1,'']]],
  ['miscellaneous_11',['Miscellaneous',['../md_vendor_2imgui_2docs_2EXAMPLES.html#autotoc_md68',1,'']]],
  ['missing_20glyph_20ranges_12',['(3) Missing glyph ranges.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md165',1,'']]],
  ['monospace_20fonts_13',['MONOSPACE FONTS',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md219',1,'']]],
  ['mouse_20keyboard_20or_20screen_20input_20share_20remote_20display_14',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['mouse_20keyboard_20to_20dear_20imgui_20or_20my_20application_15',['Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md85',1,'']]],
  ['move_20windows_20around_16',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['multiple_20fonts_17',['Q: How can I load multiple fonts?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md137',1,'']]],
  ['multiple_20widgets_20with_20the_20same_20label_18',['Q: How can I have multiple widgets with the same label?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md109',1,'']]],
  ['multiple_20windows_20with_20the_20same_20label_19',['Q: How can I have multiple windows with the same label?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md110',1,'']]],
  ['multithreaded_20',['MultiThreaded',['../structgofpp_1_1MultiThreaded.html',1,'gofpp']]],
  ['my_20application_21',['my application',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md172',1,'How should I handle DPI in my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md134',1,'Q: How can I easily use icons in my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md85',1,'Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md130',1,'Q: How should I handle DPI in my application?']]],
  ['my_20engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_22',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['my_20engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_23',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['my_20engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_24',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['my_20own_20backend_25',['Q: How can I create my own backend?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md94',1,'']]],
  ['my_20own_20maths_20types_20instead_20of_20imvec2_20imvec4_26',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md120',1,'']]],
  ['my_20widget_20not_20reacting_20when_20i_20click_20on_20it_27',['Q: Why is my widget not reacting when I click on it?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md106',1,'']]]
];
