var searchData=
[
  ['a_20custom_20engine_0',['Using a custom engine?',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md54',1,'']]],
  ['a_20different_20font_20than_20the_20default_1',['Q: How can I load a different font than the default?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md131',1,'']]],
  ['a_20framework_2',['Not a Framework',['../md_docs_2PHILOSOPHY.html#autotoc_md27',1,'']]],
  ['a_20machine_20without_20mouse_20keyboard_20or_20screen_20input_20share_20remote_20display_3',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['a_20pull_20request_4',['How to open a Pull Request',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md63',1,'']]],
  ['a_20test_20file_5',['1. Create a test file',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md273',1,'']]],
  ['a_3a_20basics_6',['Q&amp;A: Basics',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md71',1,'']]],
  ['a_3a_20community_7',['Q&amp;A: Community',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md156',1,'']]],
  ['a_3a_20concerns_8',['Q&amp;A: Concerns',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md143',1,'']]],
  ['a_3a_20fonts_20text_9',['Q&amp;A: Fonts, Text',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md129',1,'']]],
  ['a_3a_20integration_10',['Q&amp;A: Integration',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md81',1,'']]],
  ['a_3a_20usage_11',['Q&amp;A: Usage',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md104',1,'']]],
  ['about_20filenames_12',['About Filenames',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md203',1,'']]],
  ['about_20gamma_20correct_20blending_13',['About Gamma Correct Blending',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md258',1,'']]],
  ['about_20the_20id_20stack_20system_14',['Q: About the ID Stack system...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md105',1,'']]],
  ['about_20utf_208_20encoding_15',['About UTF-8 Encoding',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md206',1,'']]],
  ['abstract_5ffactory_2ehpp_16',['abstract_factory.hpp',['../abstract__factory_8hpp.html',1,'']]],
  ['accept_17',['accept',['../classgofpp_1_1Visitable.html#adf8d6312724e6482f551e1fa17d0ac3f',1,'gofpp::Visitable']]],
  ['adapter_2ehpp_18',['adapter.hpp',['../adapter_8hpp.html',1,'']]],
  ['add_19',['add',['../classgofpp_1_1Composite.html#a0e0c87f22b56e83f9b529f64c2dc66ae',1,'gofpp::Composite']]],
  ['adding_20new_20patterns_20',['4. Adding New Patterns',['../md_docs_2CONTRIBUTING.html#autotoc_md9',1,'']]],
  ['adding_20support_20for_20tt_20imguibackendflags_5frendererhastextures_20tt_201_2092_21',['Rendering: Adding support for &lt;tt&gt;ImGuiBackendFlags_RendererHasTextures&lt;/tt&gt; (1.92+)',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md57',1,'']]],
  ['advice_22',['Getting Started &amp; General Advice',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md60',1,'']]],
  ['agreement_23',['Copyright / Contributor License Agreement',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md64',1,'']]],
  ['an_20empty_20label_24',['Q: How can I have widgets with an empty label?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md108',1,'']]],
  ['an_20image_25',['Q: How can I display an image?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md113',1,'']]],
  ['an_20issue_26',['How to open an issue',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md62',1,'']]],
  ['and_20customization_27',['Color and Customization',['..//home/runner/work/gofpp/gofpp/vendor/NTest/vendor/NCLI/README.md#autotoc_md285',1,'']]],
  ['and_20input_20non_20latin_20characters_20such_20as_20chinese_20japanese_20korean_20cyrillic_28',['Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md140',1,'']]],
  ['and_20little_20squares_20are_20showing_20instead_20of_20text_29',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['and_20macos_30',['On Ubuntu 14.04+ and macOS',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_allegro5/README.md#autotoc_md236',1,'']]],
  ['and_20plutovg_31',['Using plutosvg (and plutovg)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md265',1,'']]],
  ['and_20run_32',['2. Compile and run',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md274',1,'']]],
  ['and_20similar_20unixes_33',['and similar unixes',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md253',1,'Linux and similar Unixes'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md246',1,'Linux and similar Unixes']]],
  ['and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_34',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_35',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['and_20std_3a_3avector_36',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md123',1,'']]],
  ['api_37',['Q: How can I display custom shapes? (using low-level ImDrawList API)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md126',1,'']]],
  ['app_5ffacade_2ehpp_38',['app_facade.hpp',['../app__facade_8hpp.html',1,'']]],
  ['appfacade_39',['appfacade',['../classAppFacade.html',1,'AppFacade'],['../classAppFacade.html#ab4466dd8a2d133620f9709faf71220b7',1,'AppFacade::AppFacade()']]],
  ['application_40',['application',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md172',1,'How should I handle DPI in my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md134',1,'Q: How can I easily use icons in my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md85',1,'Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md130',1,'Q: How should I handle DPI in my application?']]],
  ['applications_41',['Examples Applications',['../md_vendor_2imgui_2docs_2EXAMPLES.html#autotoc_md67',1,'']]],
  ['are_20backends_42',['What are Backends?',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md48',1,'']]],
  ['are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_43',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['are_20displaying_20outside_20their_20expected_20windows_20boundaries_44',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['are_20imtextureid_20imtextureref_45',['Q: What are ImTextureID/ImTextureRef?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md114',1,'']]],
  ['are_20showing_20instead_20of_20text_46',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['around_47',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['as_20chinese_20japanese_20korean_20cyrillic_48',['Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md140',1,'']]],
  ['as_20opposed_20to_20c_49',['Q: Why using C++ (as opposed to C)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md153',1,'']]],
  ['as_20std_3a_3astring_20and_20std_3a_3avector_50',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md123',1,'']]],
  ['ascii_20strings_51',['(2) Invalid UTF-8 encoding of your non-ASCII strings.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md164',1,'']]],
  ['asked_20questions_52',['FAQ (Frequently Asked Questions)',['../md_vendor_2imgui_2docs_2FAQ.html',1,'']]],
  ['asked_20questions_20faq_53',['Support, Frequently Asked Questions (FAQ)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md229',1,'']]],
  ['assertions_54',['Assertions',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md276',1,'']]],
  ['atlas_20texture_20fails_20to_20upload_20to_20gpu_55',['(4) Font atlas texture fails to upload to GPU.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md166',1,'']]]
];
