var searchData=
[
  ['observable_0',['Observable',['../classgofpp_1_1Observable.html',1,'gofpp']]],
  ['observer_1',['Observer',['../classgofpp_1_1Observer.html',1,'gofpp']]],
  ['observer_2ehpp_2',['observer.hpp',['../observer_8hpp.html',1,'']]],
  ['observer_3c_20historyevent_20_3e_3',['Observer&lt; HistoryEvent &gt;',['../classgofpp_1_1Observer.html',1,'gofpp']]],
  ['of_20dear_20imgui_4',['Q: Can you reskin the look of Dear ImGui?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md150',1,'']]],
  ['of_20imvec2_20imvec4_5',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md120',1,'']]],
  ['of_20standard_20backends_6',['List of standard Backends',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md50',1,'']]],
  ['of_20text_7',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['of_20tt_20tt_20or_20unexpected_20working_20directory_8',['(1) Invalid filename due to use of &lt;tt&gt;\&lt;/tt&gt; or unexpected working directory.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md163',1,'']]],
  ['of_20your_20non_20ascii_20strings_9',['(2) Invalid UTF-8 encoding of your non-ASCII strings.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md164',1,'']]],
  ['on_20a_20machine_20without_20mouse_20keyboard_20or_20screen_20input_20share_20remote_20display_10',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['on_20it_11',['Q: Why is my widget not reacting when I click on it?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md106',1,'']]],
  ['on_20one_12',['Q: Why is the wrong widget reacting when I click on one?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md107',1,'']]],
  ['on_20ubuntu_2014_2004_20and_20macos_13',['On Ubuntu 14.04+ and macOS',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_allegro5/README.md#autotoc_md236',1,'']]],
  ['on_20windows_20with_20visual_20studio_20s_20cli_14',['On Windows with Visual Studio&apos;s CLI',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_allegro5/README.md#autotoc_md237',1,'']]],
  ['one_15',['Q: Why is the wrong widget reacting when I click on one?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md107',1,'']]],
  ['onnotify_16',['onnotify',['../structHistoryObserver.html#afbafe11cbbe4a59ad739d733b528559e',1,'HistoryObserver::onNotify()'],['../classgofpp_1_1Observer.html#adedfe2ba9bca3461d43d9cb9feb0078b',1,'gofpp::Observer::onNotify()']]],
  ['op_17',['op',['../structCalcCommand.html#aafca85b839a2b03895d49f39e5d16f54',1,'CalcCommand']]],
  ['open_20a_20pull_20request_18',['How to open a Pull Request',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md63',1,'']]],
  ['open_20an_20issue_19',['How to open an issue',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md62',1,'']]],
  ['opentype_20svg_20fonts_20svginot_20',['Using OpenType SVG fonts (SVGinOT)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md263',1,'']]],
  ['operation_21',['operation',['../classgofpp_1_1Composite.html#a5a6ca0cd9031f26e9e576b92dcb2bc01',1,'gofpp::Composite']]],
  ['operator_3d_22',['operator=',['../classgofpp_1_1Singleton.html#a15f04b491d8993cbbc9625ad2fde1e2f',1,'gofpp::Singleton']]],
  ['operators_20with_20imvec2_23',['Q: How can I use maths operators with ImVec2?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md117',1,'']]],
  ['opposed_20to_20c_24',['Q: Why using C++ (as opposed to C)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md153',1,'']]],
  ['or_20disappearing_20when_20i_20move_20windows_20around_25',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['or_20gamepad_20controls_26',['Q: How can I enable keyboard or gamepad controls?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md88',1,'']]],
  ['or_20my_20application_27',['Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md85',1,'']]],
  ['or_20screen_20input_20share_20remote_20display_28',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['or_20unexpected_20working_20directory_29',['(1) Invalid filename due to use of &lt;tt&gt;\&lt;/tt&gt; or unexpected working directory.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md163',1,'']]],
  ['output_30',['Example Output',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md278',1,'']]],
  ['outside_20their_20expected_20windows_20boundaries_31',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['overlapping_20ranges_32',['Excluding Overlapping Ranges',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md187',1,'']]],
  ['overview_33',['Patterns Overview',['../index.html#autotoc_md37',1,'']]],
  ['own_20backend_34',['own backend',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md94',1,'Q: How can I create my own backend?'],['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md53',1,'Writing your own Backend']]],
  ['own_20maths_20types_20instead_20of_20imvec2_20imvec4_35',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md120',1,'']]]
];
