var searchData=
[
  ['data_20embedded_20in_20source_20code_0',['Loading Font Data Embedded In Source Code',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md181',1,'']]],
  ['data_20from_20memory_1',['Loading Font Data from Memory',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md178',1,'']]],
  ['dear_20imgui_2',['dear imgui',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md147',1,'Q: Can you create elaborate/serious tools with Dear ImGui?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md150',1,'Q: Can you reskin the look of Dear ImGui?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md144',1,'Q: Who uses Dear ImGui?']]],
  ['dear_20imgui_20in_20my_20engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_3',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['dear_20imgui_20in_20my_20engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_4',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['dear_20imgui_20in_20my_20engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_5',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['dear_20imgui_20or_20my_20application_6',['Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md85',1,'']]],
  ['dear_20imgui_3a_20backends_7',['Dear ImGui: Backends',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md44',1,'']]],
  ['dear_20imgui_3a_20examples_8',['Dear ImGui: Examples',['../md_vendor_2imgui_2docs_2EXAMPLES.html#autotoc_md65',1,'']]],
  ['dear_20imgui_3a_20using_20fonts_9',['Dear ImGui: Using Fonts',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md159',1,'']]],
  ['debug_20tools_10',['Debug Tools',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md209',1,'']]],
  ['debugger_20fonts_11',['Metrics/Debugger-&gt;Fonts',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md210',1,'']]],
  ['decorator_2ehpp_12',['decorator.hpp',['../decorator_8hpp.html',1,'']]],
  ['default_13',['Q: How can I load a different font than the default?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md131',1,'']]],
  ['demo_14',['Demo',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md226',1,'']]],
  ['dependency_15',['Dependency',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md270',1,'']]],
  ['description_16',['description',['../structHistoryEvent.html#af0f311f4600e097e76b9203f49d62f3b',1,'HistoryEvent']]],
  ['design_20process_17',['Design Process',['../md_docs_2PHILOSOPHY.html#autotoc_md26',1,'']]],
  ['developers_18',['Testbed for toying with settings (for developers)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md259',1,'']]],
  ['different_20font_20than_20the_20default_19',['Q: How can I load a different font than the default?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md131',1,'']]],
  ['directory_20',['(1) Invalid filename due to use of &lt;tt&gt;\&lt;/tt&gt; or unexpected working directory.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md163',1,'']]],
  ['disappearing_20when_20i_20move_20windows_20around_21',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['discussions_22',['&apos;Issues&apos; vs &apos;Discussions&apos;',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md61',1,'']]],
  ['dispatch_20mouse_20keyboard_20to_20dear_20imgui_20or_20my_20application_23',['Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md85',1,'']]],
  ['display_24',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['display_20an_20image_25',['Q: How can I display an image?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md113',1,'']]],
  ['display_20and_20input_20non_20latin_20characters_20such_20as_20chinese_20japanese_20korean_20cyrillic_26',['Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md140',1,'']]],
  ['display_20custom_20shapes_20using_20low_20level_20imdrawlist_20api_27',['Q: How can I display custom shapes? (using low-level ImDrawList API)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md126',1,'']]],
  ['displaying_20outside_20their_20expected_20windows_20boundaries_28',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['docommand_29',['doCommand',['../classgofpp_1_1CommandStack.html#a399d4077e7c27a21909e56f85fc85091',1,'gofpp::CommandStack']]],
  ['documentation_30',['documentation',['../md_docs_2CONTRIBUTING.html#autotoc_md13',1,'6. Documentation'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md72',1,'Q: Where is the documentation?']]],
  ['documentation_20guide_31',['GoF++ Header Documentation Guide',['../md_docs_2HEADER__DOCS__GUIDE.html',1,'']]],
  ['doxygen_32',['Doxygen',['../index.html#autotoc_md41',1,'']]],
  ['dpi_20in_20my_20application_33',['dpi in my application',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md172',1,'How should I handle DPI in my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md130',1,'Q: How should I handle DPI in my application?']]],
  ['due_20to_20use_20of_20tt_20tt_20or_20unexpected_20working_20directory_34',['(1) Invalid filename due to use of &lt;tt&gt;\&lt;/tt&gt; or unexpected working directory.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md163',1,'']]],
  ['dynamic_20fonts_20system_20in_201_2092_20june_202025_35',['New! Dynamic Fonts system in 1.92 (June 2025)',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md169',1,'']]]
];
