var searchData=
[
  ['easily_20use_20icons_20in_20my_20application_0',['Q: How can I easily use icons in my application?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md134',1,'']]],
  ['elaborate_20serious_20tools_20with_20dear_20imgui_1',['Q: Can you create elaborate/serious tools with Dear ImGui?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md147',1,'']]],
  ['elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_2',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_3',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['embedded_20in_20source_20code_4',['Loading Font Data Embedded In Source Code',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md181',1,'']]],
  ['emojis_5',['emojis',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md262',1,'Colorful glyphs/emojis'],['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md193',1,'Using Colorful Glyphs/Emojis']]],
  ['empty_20label_6',['Q: How can I have widgets with an empty label?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md108',1,'']]],
  ['emscripten_7',['emscripten',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md248',1,'Emscripten'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md255',1,'Emscripten']]],
  ['enable_20keyboard_20or_20gamepad_20controls_8',['Q: How can I enable keyboard or gamepad controls?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md88',1,'']]],
  ['encoding_9',['About UTF-8 Encoding',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md206',1,'']]],
  ['encoding_20of_20your_20non_20ascii_20strings_10',['(2) Invalid UTF-8 encoding of your non-ASCII strings.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md164',1,'']]],
  ['encoding_20viewer_11',['UTF-8 Encoding Viewer**',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md211',1,'']]],
  ['engine_12',['Using a custom engine?',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md54',1,'']]],
  ['engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_13',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_14',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_15',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['enter_16',['enter',['../classgofpp_1_1State.html#aeb368391d27d42ffb6afa68334f6ee9f',1,'gofpp::State']]],
  ['example_17',['example',['../md_docs_2HEADER__DOCS__GUIDE.html#autotoc_md22',1,'Example'],['../index.html#autotoc_md36',1,'Example']]],
  ['example_20contribution_20flow_18',['8. Example Contribution Flow',['../md_docs_2CONTRIBUTING.html#autotoc_md17',1,'']]],
  ['example_20output_19',['Example Output',['..//home/runner/work/gofpp/gofpp/vendor/NTest/README.md#autotoc_md278',1,'']]],
  ['example_20usage_20',['Example Usage',['../proxy_8hpp.html#usage',1,'']]],
  ['examples_21',['examples',['../md_vendor_2imgui_2docs_2EXAMPLES.html#autotoc_md65',1,'Dear ImGui: Examples'],['../md_vendor_2imgui_2docs_2EXAMPLES.html',1,'EXAMPLES']]],
  ['examples_20applications_22',['Examples Applications',['../md_vendor_2imgui_2docs_2EXAMPLES.html#autotoc_md67',1,'']]],
  ['examples_2emd_23',['EXAMPLES.md',['../EXAMPLES_8md.html',1,'']]],
  ['excluding_20overlapping_20ranges_24',['Excluding Overlapping Ranges',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md187',1,'']]],
  ['execute_25',['execute',['../classgofpp_1_1Context.html#a4ed2653b2fe2f81853d87724a8bd7c57',1,'gofpp::Context::execute()'],['../structgofpp_1_1ICommand.html#adb9a54c6035b8bf5b42255e1d366bbff',1,'gofpp::ICommand::execute()'],['../structCalcCommand.html#af64a132e3e6c333917b9deb50324d85e',1,'CalcCommand::execute()']]],
  ['exit_26',['exit',['../classgofpp_1_1State.html#a984bc0b5437a544dde6f612cca6831fc',1,'gofpp::State']]],
  ['expected_20windows_20boundaries_27',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['expression_28',['Expression',['../classgofpp_1_1Expression.html',1,'gofpp']]]
];
