var searchData=
[
  ['s_20cli_0',['s cli',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_allegro5/README.md#autotoc_md237',1,'On Windows with Visual Studio&apos;s CLI'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md252',1,'Windows with Visual Studio&apos;s CLI'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md245',1,'Windows with Visual Studio&apos;s CLI']]],
  ['s_20ide_1',['s ide',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md251',1,'Windows with Visual Studio&apos;s IDE'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md244',1,'Windows with Visual Studio&apos;s IDE']]],
  ['same_20label_2',['same label',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md109',1,'Q: How can I have multiple widgets with the same label?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md110',1,'Q: How can I have multiple windows with the same label?']]],
  ['save_3',['save',['../structCalcOriginator.html#a724487adbaf3eaa4a897620bfaa2e0bf',1,'CalcOriginator']]],
  ['scientificstate_4',['ScientificState',['../structScientificState.html',1,'']]],
  ['screen_20input_20share_20remote_20display_5',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['serious_20tools_20with_20dear_20imgui_6',['Q: Can you create elaborate/serious tools with Dear ImGui?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md147',1,'']]],
  ['setimpl_7',['setImpl',['../classgofpp_1_1Bridge.html#a97dfd687a7c87ae6fa458708b50eb2c6',1,'gofpp::Bridge']]],
  ['setnext_8',['setNext',['../classgofpp_1_1Handler.html#aa62a6a99a6230e9a135d16b365d2fdeb',1,'gofpp::Handler']]],
  ['setstrategy_9',['setStrategy',['../classgofpp_1_1Context.html#ab86261418ff41d9c9aab36b988de6d74',1,'gofpp::Context']]],
  ['settings_20for_20developers_10',['Testbed for toying with settings (for developers)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md259',1,'']]],
  ['shapes_20using_20low_20level_20imdrawlist_20api_11',['Q: How can I display custom shapes? (using low-level ImDrawList API)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md126',1,'']]],
  ['share_20remote_20display_12',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md91',1,'']]],
  ['should_20i_20get_13',['Q: Which version should I get?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md78',1,'']]],
  ['should_20i_20handle_20dpi_20in_20my_20application_14',['should i handle dpi in my application',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md172',1,'How should I handle DPI in my application?'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md130',1,'Q: How should I handle DPI in my application?']]],
  ['showing_20instead_20of_20text_15',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['shutdown_16',['shutdown',['../classgofpp_1_1IFacade.html#a81e2d3115e7e671f7140df102bc6c048',1,'gofpp::IFacade']]],
  ['similar_20unixes_17',['similar unixes',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md246',1,'Linux and similar Unixes'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md253',1,'Linux and similar Unixes']]],
  ['singlethreaded_18',['SingleThreaded',['../structgofpp_1_1SingleThreaded.html',1,'gofpp']]],
  ['singleton_19',['singleton',['../classgofpp_1_1Singleton.html#a5a519741348100fa396410066e5ac978',1,'gofpp::Singleton::Singleton()=default'],['../classgofpp_1_1Singleton.html#aae4393ec14db2f363f5bd61f582e28b2',1,'gofpp::Singleton::Singleton(const Singleton &amp;)=delete'],['../classgofpp_1_1Singleton.html',1,'gofpp::Singleton&lt; T, ThreadPolicy &gt;']]],
  ['singleton_2ehpp_20',['singleton.hpp',['../singleton_8hpp.html',1,'']]],
  ['some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_21',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md100',1,'']]],
  ['some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_22',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md101',1,'']]],
  ['source_20code_23',['Loading Font Data Embedded In Source Code',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md181',1,'']]],
  ['sponsors_24',['Sponsors',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md231',1,'']]],
  ['squares_20are_20showing_20instead_20of_20text_25',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md97',1,'']]],
  ['stack_20system_26',['Q: About the ID Stack system...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md105',1,'']]],
  ['standard_20backends_27',['standard backends',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md50',1,'List of standard Backends'],['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md49',1,'Using standard Backends']]],
  ['standard_20c_20types_20such_20as_20std_3a_3astring_20and_20std_3a_3avector_28',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md123',1,'']]],
  ['started_29',['started',['../md_vendor_2imgui_2docs_2EXAMPLES.html#autotoc_md66',1,'Getting Started'],['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md47',1,'Getting Started'],['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md82',1,'Q: How to get started?']]],
  ['started_20general_20advice_30',['Getting Started &amp; General Advice',['../md_vendor_2imgui_2docs_2CONTRIBUTING.html#autotoc_md60',1,'']]],
  ['started_20integration_31',['Getting Started &amp; Integration',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md227',1,'']]],
  ['state_32',['state',['../classgofpp_1_1State.html',1,'gofpp::State&lt; Context &gt;'],['../structgofpp_1_1Memento.html#a9d24b21677944edf7cdebe5ee6cb0524',1,'gofpp::Memento::state']]],
  ['state_2ehpp_33',['state.hpp',['../state_8hpp.html',1,'']]],
  ['statemachine_34',['statemachine',['../classgofpp_1_1StateMachine.html#aca22601237cfeeefb248779675d4529a',1,'gofpp::StateMachine::StateMachine()'],['../classgofpp_1_1StateMachine.html',1,'gofpp::StateMachine&lt; Context &gt;']]],
  ['states_2ehpp_35',['states.hpp',['../states_8hpp.html',1,'']]],
  ['std_3a_3astring_20and_20std_3a_3avector_36',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md123',1,'']]],
  ['std_3a_3avector_37',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md123',1,'']]],
  ['step1_38',['step1',['../classgofpp_1_1TemplateBase.html#a3e66a7040eee24fff0ce7c0d7ec982bb',1,'gofpp::TemplateBase']]],
  ['step2_39',['step2',['../classgofpp_1_1TemplateBase.html#a64e0e987c136bae92c3263fa713289ab',1,'gofpp::TemplateBase']]],
  ['strategy_2ehpp_40',['strategy.hpp',['../strategy_8hpp.html',1,'']]],
  ['strings_41',['(2) Invalid UTF-8 encoding of your non-ASCII strings.',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md164',1,'']]],
  ['structural_42',['Structural',['../index.html#autotoc_md39',1,'']]],
  ['studio_20s_20cli_43',['studio s cli',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_allegro5/README.md#autotoc_md237',1,'On Windows with Visual Studio&apos;s CLI'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md252',1,'Windows with Visual Studio&apos;s CLI'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md245',1,'Windows with Visual Studio&apos;s CLI']]],
  ['studio_20s_20ide_44',['studio s ide',['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl3_opengl3/README.md#autotoc_md251',1,'Windows with Visual Studio&apos;s IDE'],['..//home/runner/work/gofpp/gofpp/vendor/imgui/examples/example_sdl2_opengl3/README.md#autotoc_md244',1,'Windows with Visual Studio&apos;s IDE']]],
  ['style_45',['3. Code Style',['../md_docs_2CONTRIBUTING.html#autotoc_md7',1,'']]],
  ['subscribe_46',['subscribe',['../classgofpp_1_1Observable.html#a1ff6d95c634093a5a8c75fe3ae6d98e9',1,'gofpp::Observable']]],
  ['such_20as_20chinese_20japanese_20korean_20cyrillic_47',['Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md140',1,'']]],
  ['such_20as_20std_3a_3astring_20and_20std_3a_3avector_48',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md123',1,'']]],
  ['support_20for_20tt_20imguibackendflags_5frendererhastextures_20tt_201_2092_49',['Rendering: Adding support for &lt;tt&gt;ImGuiBackendFlags_RendererHasTextures&lt;/tt&gt; (1.92+)',['../md_vendor_2imgui_2docs_2BACKENDS.html#autotoc_md57',1,'']]],
  ['support_20frequently_20asked_20questions_20faq_50',['Support, Frequently Asked Questions (FAQ)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/docs/README.md#autotoc_md229',1,'']]],
  ['svg_20fonts_20svginot_51',['Using OpenType SVG fonts (SVGinOT)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md263',1,'']]],
  ['svginot_52',['Using OpenType SVG fonts (SVGinOT)',['..//home/runner/work/gofpp/gofpp/vendor/imgui/misc/freetype/README.md#autotoc_md263',1,'']]],
  ['system_53',['Q: About the ID Stack system...',['../md_vendor_2imgui_2docs_2FAQ.html#autotoc_md105',1,'']]],
  ['system_20in_201_2092_20june_202025_54',['New! Dynamic Fonts system in 1.92 (June 2025)',['../md_vendor_2imgui_2docs_2FONTS.html#autotoc_md169',1,'']]]
];
