name: GoF++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  build-test-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo with submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ doxygen graphviz libsdl2-dev

      # 3. Configure and build
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DGOFPP_TEST=true ..

      # 4. Build tests (header-only, but ensures CMake works)
      - name: Build
        run: |
          cd build
          make -j$(nproc)

      # 5. Run tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # 6. Generate Doxygen docs
      - name: Generate documentation
        run: |
          doxygen Doxyfile

      # 7. Deploy to GitHub Pages (only on main branch)
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doxygen/html
